kind: Service
apiVersion: v1
metadata:
  name: session-scaler
spec:
  selector:
    app: session-scaler
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.scaler.grpcPort }}
      targetPort: {{ .Values.scaler.grpcPort }}
